public enum Genre {
    ACTION, ADVENTURE, COMEDY, DRAMA, HORROR, SF,
    FANTASY, ROMANCE, MYSTERY, THRILLER, CRIME, BIOGRAPHY, WAR,
    COOKING, TRAVEL, DOCUMENTARY, HISTORY, SPORTS, MUSIC, NEWS, TALK_SHOW
}
